#
# FILE        :app.yaml
# DATE        :2017.12.20
# DESCRIPTION :アプリケーション設定
# NAME        :Hikaru Yoshida
#

# 言語
runtime: python27

# APIバージョン
api_version: 1

# マルチスレッド
threadsafe: true

# URLと挙動
handlers:

# staticの参照とアップロード
- url: /(.*\.(css|ico|js))$
  static_files: static/\1
  upload: static/(.*\.(css|ico|js))$

# その他はmain.appを実行
- url: /.*
  script: main.app

# 使用するライブラリとバージョン
libraries:

# jinja2テンプレートエンジン
- name: jinja2
  version: latest

# Google App Engine API
- name: webapp2
  version: latest

automatic_scaling:
  # 補欠インスタンス数
  min_idle_instances: 1
  # 待機インスタンス数
  max_idle_instances: 1
  # インスタンス生成までの待機時間下限
  min_pending_latency: 30ms
  # インスタンス生成までの待機時間上限
  max_pending_latency: 30ms
  # 1インスタンスあたりの処理量設定
  max_concurrent_requests: 4
